In [2]:
import pandas as pd

df = pd.read_csv("/content/neu-boston-boys_2025-02-09_export.csv")

In [3]:
df

,Date,Description,Category,Cost,Currency,Aman Rao,Vishwajeet Hogale,Suraj Patel M,Atta
0,2024-08-15,Boston hotel,Hotel,49120.08,INR,-16373.36,32746.72,0.00,-16373.36
1,2024-08-15,Atta paid Vishwajeet H.,Payment,16373.36,INR,0.00,-16373.36,0.00,16373.36
2,2024-08-16,Aman R. paid Vishwajeet H.,Payment,16373.36,INR,16373.36,-16373.36,0.00,0.00
3,2024-08-30,TB dinner,Dining out,1470.00,INR,-490.00,-490.00,0.00,980.00
4,2024-08-30,Pain au chocolat,General,706.00,INR,470.67,-235.33,0.00,-235.34
...,...,...,...,...,...,...,...,...,...
358,2025-02-09,You know what,General,18.15,USD,0.00,-6.05,12.10,-6.05
359,2025-02-09,Tomatoes,General,4.70,USD,0.00,0.00,4.70,-4.70
360,2025-02-09,Tropical,General,39.04,USD,-9.76,-9.76,29.28,-9.76
361,2025-02-09,Total balance,,,INR,0.00,0.00,0.00,0.00
362,2025-02-09,Total balance,,,USD,194.63,-463.12,-31.01,299.50

In [4]:
df = df[df["Currency"] == 'USD']

In [5]:
df = df[df["Date"] > "2024-09-30" ]

In [6]:
len(df["Date"].unique())

103

In [7]:
df["Category"].unique()

array(['Groceries', 'Services', 'General', 'Rent', 'Payment',
       'Dining out', 'Electronics', 'Bus/train', 'TV/Phone/Internet',
       'Taxi', 'Home - Other', 'Electricity', 'Household supplies',
       'Water', 'Liquor', 'Entertainment - Other', 'Furniture',
       'Insurance', ' '], dtype=object)

In [8]:
df = df[~df["Category"].isin(['Rent', 'Furniture'])]

In [9]:
df["Category"].unique()

array(['Groceries', 'Services', 'General', 'Payment', 'Dining out',
       'Electronics', 'Bus/train', 'TV/Phone/Internet', 'Taxi',
       'Home - Other', 'Electricity', 'Household supplies', 'Water',
       'Liquor', 'Entertainment - Other', 'Insurance', ' '], dtype=object)

In [12]:
df.sort_values(by='Cost', ascending=False)

,Date,Description,Category,Cost,Currency,Aman Rao,Vishwajeet Hogale,Suraj Patel M,Atta
144,2024-11-02,Atta paid Aman R.,Payment,750.00,USD,-750.00,0.00,0.00,750.00
107,2024-10-02,Suraj P. paid Aman R.,Payment,750.00,USD,-750.00,0.00,750.00,0.00
146,2024-11-02,Vishwajeet H. paid Aman R.,Payment,750.00,USD,-750.00,750.00,0.00,0.00
98,2024-10-01,Atta paid Aman R.,Payment,750.00,USD,-750.00,0.00,0.00,750.00
145,2024-11-02,Suraj P. paid Aman R.,Payment,750.00,USD,-750.00,0.00,750.00,0.00
...,...,...,...,...,...,...,...,...,...
245,2024-12-21,Paani,General,1.89,USD,0.00,-0.63,1.26,-0.63
246,2024-12-22,Bus,Bus/train,1.70,USD,0.00,1.70,-1.70,0.00
118,2024-10-11,Bus,Bus/train,1.70,USD,0.00,-1.70,0.00,1.70
204,2024-12-01,Mint,General,1.49,USD,-0.38,-0.37,-0.37,1.12
362,2025-02-09,Total balance,,NaN,USD,194.63,-463.12,-31.01,299.50

In [13]:
df = df[~df["Description"].str.contains("paid", case=False, na=False)]

In [16]:
df

,Date,Description,Category,Cost,Currency,Aman Rao,Vishwajeet Hogale,Suraj Patel M,Atta
94,2024-10-01,Snacks,Groceries,7.78,USD,3.89,0.00,0.00,-3.89
95,2024-10-01,Laundry,Services,6.00,USD,6.00,0.00,0.00,-6.00
96,2024-10-01,Garba night tickets,General,32.00,USD,16.00,-16.00,0.00,0.00
101,2024-10-01,Wash and dry,General,6.00,USD,6.00,-6.00,0.00,0.00
102,2024-10-02,Coffee W,Dining out,5.89,USD,0.00,2.95,-2.95,0.00
...,...,...,...,...,...,...,...,...,...
357,2025-02-09,Alc,General,51.48,USD,34.32,-17.16,0.00,-17.16
358,2025-02-09,You know what,General,18.15,USD,0.00,-6.05,12.10,-6.05
359,2025-02-09,Tomatoes,General,4.70,USD,0.00,0.00,4.70,-4.70
360,2025-02-09,Tropical,General,39.04,USD,-9.76,-9.76,29.28,-9.76
362,2025-02-09,Total balance,,NaN,USD,194.63,-463.12,-31.01,299.50

In [17]:
df["Category"].unique()

array(['Groceries', 'Services', 'General', 'Dining out', 'Electronics',
       'Bus/train', 'TV/Phone/Internet', 'Taxi', 'Home - Other',
       'Electricity', 'Household supplies', 'Water', 'Liquor',
       'Entertainment - Other', 'Insurance', ' '], dtype=object)

In [18]:
df.sort_values(by='Cost', ascending=False)

,Date,Description,Category,Cost,Currency,Aman Rao,Vishwajeet Hogale,Suraj Patel M,Atta
228,2024-12-11,NYC tickets,General,231.93,USD,0.00,-77.31,-77.31,154.62
253,2024-12-27,NYC attractions,General,222.00,USD,0.00,-74.00,-74.00,148.00
317,2025-01-19,Costco,Household supplies,195.48,USD,-48.87,-48.87,-48.87,146.61
191,2024-11-27,Amans mint,General,188.48,USD,-188.48,188.48,0.00,0.00
133,2024-10-24,Groceries,Groceries,156.65,USD,-39.17,-39.16,-39.16,117.49
...,...,...,...,...,...,...,...,...,...
245,2024-12-21,Paani,General,1.89,USD,0.00,-0.63,1.26,-0.63
246,2024-12-22,Bus,Bus/train,1.70,USD,0.00,1.70,-1.70,0.00
118,2024-10-11,Bus,Bus/train,1.70,USD,0.00,-1.70,0.00,1.70
204,2024-12-01,Mint,General,1.49,USD,-0.38,-0.37,-0.37,1.12
362,2025-02-09,Total balance,,NaN,USD,194.63,-463.12,-31.01,299.50

In [19]:
df = df[~df["Description"].str.contains("NYC", case=False, na=False)]

In [21]:
# Ensure 'Cost' column is numeric
df["Cost"] = pd.to_numeric(df["Cost"], errors="coerce")

# Ensure 'Date' column is in datetime format (if necessary)
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

# Now perform the calculation
average_cost_per_date = df["Cost"].sum() / len(df["Date"].unique())

print(average_cost_per_date/4)

14.91254854368932

<ipython-input-21-f50dd0789795>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cost"] = pd.to_numeric(df["Cost"], errors="coerce")
<ipython-input-21-f50dd0789795>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"], errors="coerce")

In [23]:
# Ensure 'Date' is in datetime format
df["Date"] = pd.to_datetime(df["Date"])

# Convert 'Cost' to numeric
df["Cost"] = pd.to_numeric(df["Cost"], errors="coerce")

# Extract month
df["Month"] = df["Date"].dt.to_period("M")

# Calculate month-wise total expenditure
month_wise_expenditure = df.groupby("Month")["Cost"].sum()

# Divide by 6 for per person cost
month_wise_per_person = month_wise_expenditure / 4

# Print result
print("Month-wise per person cost:\n", month_wise_per_person.round(2))

Month-wise per person cost:
 Month
2024-10    299.42
2024-11    341.69
2024-12    407.06
2025-01    370.03
2025-02    117.79
Freq: M, Name: Cost, dtype: float64

<ipython-input-23-107b94f35c74>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"])
<ipython-input-23-107b94f35c74>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cost"] = pd.to_numeric(df["Cost"], errors="coerce")
<ipython-input-23-107b94f35c74>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Month"] = df["Date"].dt.to_period("M")